URL = "http://eplus.jp/event_name"

[[Ballots]]
Credentials = { username = "username@email.com", password = "password" }

Codes = ["aaa", "bbb"]
# You can specify a list or you can just write "All" if you want to apply for all sessions.
# Examples:
# Sessions = ["昼公演"]
# Sessions = ["昼公演", "夜公演"]
# Sessions = "All"
Sessions = "All"
Pair = true
# If your renban list is A, B, C, ..., the value you should pick is:
# A -> 1
# B -> 2
# C -> 3
# ...
# You can also find this as the "No" of the person on
# https://member.eplus.jp/update-dokosha
Renban = 1
# If there are goods, do you want to apply for them?
WantGoods = false

[[Ballots]]
Credentials = { username = "b", password = "b" }

Codes = ["bbb"]
Sessions = "昼公演"
Type = "Pair"
# TODO: Selecting by name doesn't actually work but we could try implementing it
# Renban = "aaa"
Renban = 2

[[Ballots]]
Credentials = { username = "b", password = "b" }

Codes = ["c"]
Sessions = "All"
Type = "Single"
